//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedAligner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class OpenAiSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static OpenAiSettings defaultInstance = ((OpenAiSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OpenAiSettings())));
        
        public static OpenAiSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gpt_4_1_mini")]
        public string GptModel {
            get {
                return ((string)(this["GptModel"]));
            }
            set {
                this["GptModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstReference {
            get {
                return ((string)(this["FirstReference"]));
            }
            set {
                this["FirstReference"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastReference {
            get {
                return ((string)(this["LastReference"]));
            }
            set {
                this["LastReference"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReferenceList {
            get {
                return ((string)(this["ReferenceList"]));
            }
            set {
                this["ReferenceList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxPromptVerses {
            get {
                return ((int)(this["MaxPromptVerses"]));
            }
            set {
                this["MaxPromptVerses"] = value;
            }
        }
    }
}
